spring.application.name=marketplace-backend

spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasource.username=root
spring.datasource.password=Peak0604

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
